services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blogdemo
      - POSTGRES_PASSWORD=lmnop
    expose:
      - 5432
    restart: always
  app-dc:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=blogdemo
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=lmnop
    depends_on:
      - db
    restart: always
  app-dc-2:
    build: .
    ports:
      - 8081:8080
    environment:
      - POSTGRES_DB=blogdemo
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=lmnop
    depends_on:
      - db
    restart: always
volumes:
  db-data:
