server:
  port : 8080

host:
  dns: ${SERVER_DNS}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRES_ENDPOINT}:5432/roma_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

s3:
  bucket:
    name: roman-kotov-task1-bucket

sns:
  topic-arn: arn:aws:sns:us-east-1:262160507634:t8-uploads-notification-topic

sqs:
  queueUrl: https://sqs.us-east-1.amazonaws.com/262160507634/t8-uploads-notification-queue
